CREATE DATABASE IF NOT EXISTS cursonode;

USE cursonode;

CREATE TABLE IF NOT EXISTS users(
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(50) DEFAULT NULL,
  email VARCHAR(50) DEFAULT NULL UNIQUE,
  password VARCHAR(150) DEFAULT NULL,
  role ENUM('User', 'Admin') NOT NULL DEFAULT 'User',
  age INT DEFAULT NULL,
  createdAt DATETIME DEFAULT NULL,
  updatedAt DATETIME DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS tracks(
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(150) NOT NULL,
  album VARCHAR(150) NOT NULL,
  cover VARCHAR(150) NOT NULL,
  artist_name VARCHAR(150) NOT NULL,
  artist_nickname VARCHAR(150) NOT NULL,
  artist_nationality VARCHAR(150) NOT NULL,
  duration_start INT NOT NULL,
  duration_end INT NOT NULL,
  mediaId VARCHAR(150) NOT NULL,
  createdAt DATETIME DEFAULT NULL,
  updatedAt DATETIME DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS storages(
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  url MEDIUMTEXT NOT NULL,
  filename MEDIUMTEXT NOT NULL,
  createdAt DATETIME DEFAULT NULL,
  updatedAt DATETIME DEFAULT NULL
);